//! The milestone-1 acceptance gate: every v1 gesture, replayed from a recorded
//! touch stream, must produce exactly the actions the specification calls for.
//!
//! The fixtures in `tests/fixtures/` are generated by
//! `tools/proto/make_fixtures.py` and carry the expectations the Python
//! prototype produced, so this suite also proves the Rust port did not drift
//! from the implementation the timings were tuned against.

use std::path::{Path, PathBuf};

use padremote::gesture::{Button, Config, InputAction, Recognizer, ScrollPhase, TouchSample};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    description: String,
    surface: Surface,
    samples: Vec<Sample>,
    expect: Expect,
}

#[derive(Debug, Deserialize)]
struct Surface {
    wpx: f64,
    hpx: f64,
}

#[derive(Debug, Deserialize)]
struct Sample {
    t_ms: u32,
    pointer_id: u8,
    phase: u8,
    x: f32,
    y: f32,
}

#[derive(Debug, Deserialize)]
struct Expect {
    kinds: Vec<String>,
    clicks: Vec<ClickExpect>,
    net_move: [f64; 2],
    net_scroll: [f64; 2],
    net_zoom: i32,
    #[serde(default)]
    scroll_phases: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct ClickExpect {
    button: String,
    count: u8,
}

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

fn load_all() -> Vec<Fixture> {
    let dir = fixtures_dir();
    let mut paths: Vec<_> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    paths.sort();
    assert!(!paths.is_empty(), "no fixtures in {}", dir.display());
    paths
        .iter()
        .map(|p| {
            let text = std::fs::read_to_string(p).unwrap();
            serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
        })
        .collect()
}

fn run(f: &Fixture) -> Vec<InputAction> {
    let samples: Vec<TouchSample> = f
        .samples
        .iter()
        .map(|s| TouchSample {
            t_ms: s.t_ms,
            pointer_id: s.pointer_id,
            phase: s.phase,
            x: s.x,
            y: s.y,
        })
        .collect();
    // Pinch zoom ships off - a pinch and a two-finger swipe are too alike on a
    // phone-sized surface - but the recognizer still implements it, and these
    // fixtures are what prove it. Turned on explicitly so the recorded pinches
    // are still judged.
    let mut cfg = Config::default();
    cfg.zoom.enabled = true;
    // Tap-and-drag ships off too - a tap followed by an ordinary move is not a
    // drag anybody asked for, and the phone draws nothing to say one has armed -
    // but the recognizer still implements it for the host mirror and for whoever
    // turns it on, and `tap_and_drag.json` is what proves it still works.
    cfg.drag.tap_and_drag = true;
    let mut rec = Recognizer::new(cfg, f.surface.wpx, f.surface.hpx);
    rec.feed(&samples)
}

fn button_name(b: Button) -> &'static str {
    match b {
        Button::Left => "left",
        Button::Right => "right",
        Button::Middle => "middle",
    }
}

fn sum_move(actions: &[InputAction]) -> (f64, f64) {
    actions.iter().fold((0.0, 0.0), |acc, a| match a {
        InputAction::Move { dx, dy, .. } => (acc.0 + dx, acc.1 + dy),
        _ => acc,
    })
}

fn sum_scroll(actions: &[InputAction]) -> (f64, f64) {
    actions.iter().fold((0.0, 0.0), |acc, a| match a {
        InputAction::Scroll { dx, dy, .. } => (acc.0 + dx, acc.1 + dy),
        _ => acc,
    })
}

fn sum_zoom(actions: &[InputAction]) -> i32 {
    actions
        .iter()
        .map(|a| {
            if let InputAction::Zoom { steps, .. } = a {
                *steps
            } else {
                0
            }
        })
        .sum()
}

/// The Rust engine must agree with the Python prototype action for action.
#[test]
fn matches_prototype_expectations() {
    for f in load_all() {
        let actions = run(&f);

        let kinds: Vec<&str> = actions.iter().map(|a| a.kind()).collect();
        assert_eq!(
            kinds, f.expect.kinds,
            "{}: action sequence differs from the prototype ({})",
            f.name, f.description
        );

        let clicks: Vec<(String, u8)> = actions
            .iter()
            .filter_map(|a| match a {
                InputAction::Click { button, count, .. } => {
                    Some((button_name(*button).to_string(), *count))
                }
                _ => None,
            })
            .collect();
        let want: Vec<(String, u8)> = f
            .expect
            .clicks
            .iter()
            .map(|c| (c.button.clone(), c.count))
            .collect();
        assert_eq!(clicks, want, "{}: clicks differ", f.name);

        let (mx, my) = sum_move(&actions);
        assert_eq!(
            [mx, my],
            f.expect.net_move,
            "{}: net cursor movement differs",
            f.name
        );
        let (sx, sy) = sum_scroll(&actions);
        assert_eq!(
            [sx, sy],
            f.expect.net_scroll,
            "{}: net scroll differs",
            f.name
        );
        assert_eq!(
            sum_zoom(&actions),
            f.expect.net_zoom,
            "{}: net zoom differs",
            f.name
        );

        let phases: Vec<&str> = actions
            .iter()
            .filter_map(|a| match a {
                InputAction::Scroll { phase, .. } => Some(phase.name()),
                _ => None,
            })
            .collect();
        assert_eq!(
            phases, f.expect.scroll_phases,
            "{}: scroll phases differ",
            f.name
        );
    }
}

/// The behavioural contract from plan.md section 9, asserted independently of
/// the recorded numbers - these are the properties a user would notice breaking.
#[test]
fn every_v1_gesture_behaves_as_specified() {
    for f in load_all() {
        let actions = run(&f);
        let kinds: Vec<&str> = actions.iter().map(|a| a.kind()).collect();
        let has = |k: &str| kinds.contains(&k);
        let ctx = format!("{} ({})", f.name, f.description);

        match f.name.as_str() {
            "tap_click" => {
                assert_eq!(kinds, ["click"], "{ctx}");
                assert!(
                    matches!(
                        actions[0],
                        InputAction::Click {
                            button: Button::Left,
                            count: 1,
                            ..
                        }
                    ),
                    "{ctx}"
                );
            }
            "double_tap" => {
                let counts: Vec<u8> = actions
                    .iter()
                    .filter_map(|a| match a {
                        InputAction::Click { count, .. } => Some(*count),
                        _ => None,
                    })
                    .collect();
                assert_eq!(counts, [1, 2], "{ctx}: second tap must click with count 2");
            }
            "two_finger_tap_rightclick" => {
                assert!(
                    matches!(
                        actions[..],
                        [InputAction::Click {
                            button: Button::Right,
                            ..
                        }]
                    ),
                    "{ctx}: got {actions:?}"
                );
            }
            "three_finger_tap_middleclick" => {
                assert!(
                    matches!(
                        actions[..],
                        [InputAction::Click {
                            button: Button::Middle,
                            ..
                        }]
                    ),
                    "{ctx}: got {actions:?}"
                );
            }
            "one_finger_move" => {
                assert!(
                    kinds.iter().all(|k| *k == "move"),
                    "{ctx}: expected only moves"
                );
                let (dx, dy) = sum_move(&actions);
                assert!(
                    dx > 0.0 && dy < 0.0,
                    "{ctx}: expected net travel right and up"
                );
            }
            "two_finger_scroll" => {
                assert!(has("scroll"), "{ctx}");
                // Without an opening and closing phase macOS treats these as
                // mouse-wheel notches: no smoothing, no rubber-banding.
                let phases: Vec<ScrollPhase> = actions
                    .iter()
                    .filter_map(|a| match a {
                        InputAction::Scroll { phase, .. } => Some(*phase),
                        _ => None,
                    })
                    .collect();
                assert_eq!(
                    phases.first(),
                    Some(&ScrollPhase::Begin),
                    "{ctx}: must open the gesture"
                );
                assert_eq!(
                    phases.last(),
                    Some(&ScrollPhase::End),
                    "{ctx}: must close the gesture"
                );
                assert!(
                    phases[1..phases.len() - 1]
                        .iter()
                        .all(|p| *p == ScrollPhase::Continue),
                    "{ctx}: everything between the edges must be a continue phase"
                );
                assert!(
                    !has("zoom"),
                    "{ctx}: parallel movement must not read as zoom"
                );
                assert!(!has("move"), "{ctx}: two fingers must not move the cursor");
                assert!(
                    sum_scroll(&actions).1 < 0.0,
                    "{ctx}: fingers up should scroll dy < 0"
                );
            }
            "pinch_out_zoom_in" => {
                assert!(
                    sum_zoom(&actions) > 0,
                    "{ctx}: separating fingers must zoom in"
                );
                assert!(!has("scroll"), "{ctx}: a pinch must not also scroll");
            }
            "pinch_in_zoom_out" => {
                assert!(
                    sum_zoom(&actions) < 0,
                    "{ctx}: converging fingers must zoom out"
                );
            }
            "press_and_drag" | "tap_and_drag" => {
                let downs = kinds.iter().filter(|k| **k == "button_down").count();
                let ups = kinds.iter().filter(|k| **k == "button_up").count();
                assert_eq!(
                    (downs, ups),
                    (1, 1),
                    "{ctx}: exactly one press and one release"
                );
                let d = kinds.iter().position(|k| *k == "button_down").unwrap();
                let u = kinds.iter().position(|k| *k == "button_up").unwrap();
                assert!(d < u, "{ctx}: release must follow press");
                assert!(
                    kinds[d..u].contains(&"move"),
                    "{ctx}: cursor must move while held"
                );
                if f.name == "tap_and_drag" {
                    assert_eq!(kinds[0], "click", "{ctx}: starts with the tap's click");
                }
            }
            "drag_cancelled" => {
                assert_eq!(
                    kinds.iter().filter(|k| **k == "button_up").count(),
                    1,
                    "{ctx}: a cancelled drag must still release the button"
                );
                assert_eq!(
                    kinds.last(),
                    Some(&"button_up"),
                    "{ctx}: release must be last"
                );
            }
            other => panic!("fixture {other} has no behavioural assertions"),
        }
    }
}

/// Losing the phone mid-drag must never leave a button held (section 9.8).
#[test]
fn release_all_frees_a_held_button() {
    let mut cfg = Config::default();
    cfg.zoom.enabled = true;
    let mut rec = Recognizer::new(cfg, 390.0, 716.0);
    // Press and hold past pressMs (500 ms), then move: that is a drag.
    let mut samples = vec![TouchSample {
        t_ms: 0,
        pointer_id: 0,
        phase: 0,
        x: 0.4,
        y: 0.5,
    }];
    for i in 1..80 {
        samples.push(TouchSample {
            t_ms: i * 8,
            pointer_id: 0,
            phase: 1,
            x: 0.4,
            y: 0.5,
        });
    }
    samples.push(TouchSample {
        t_ms: 700,
        pointer_id: 0,
        phase: 1,
        x: 0.7,
        y: 0.5,
    });
    let actions = rec.feed(&samples);
    assert!(
        actions.iter().any(|a| matches!(
            a,
            InputAction::ButtonDown {
                button: Button::Left,
                ..
            }
        )),
        "expected the drag to press the left button: {actions:?}"
    );

    let released = rec.release_all();
    assert!(
        released
            .iter()
            .any(|a| matches!(a, InputAction::ButtonUp(Button::Left))),
        "release_all must lift the held button: {released:?}"
    );
    assert!(
        rec.release_all().is_empty(),
        "releasing twice must be a no-op"
    );
}

/// A malformed frame is dropped, not fatal.
#[test]
fn frame_round_trip_and_rejection() {
    let samples = vec![
        TouchSample {
            t_ms: 1,
            pointer_id: 3,
            phase: 0,
            x: 0.25,
            y: 0.75,
        },
        TouchSample {
            t_ms: 9,
            pointer_id: 3,
            phase: 1,
            x: 0.30,
            y: 0.70,
        },
    ];
    let encoded = padremote::protocol::encode_frame(&samples);
    assert_eq!(encoded.len(), 2 + 14 * 2);
    assert_eq!(
        padremote::protocol::decode_frame(&encoded).unwrap(),
        samples
    );

    assert!(padremote::protocol::decode_frame(&[]).is_none());
    assert!(
        padremote::protocol::decode_frame(&[9, 0]).is_none(),
        "wrong version"
    );
    assert!(
        padremote::protocol::decode_frame(&[1, 5, 0, 0]).is_none(),
        "truncated"
    );
}
