//! Bake the phone page into the binary.
//!
//! Until now the page came from `npm run dev` on a second port, which made the
//! product two processes the user had to know about: quit the terminal, or
//! reboot, and the menu-bar app kept running while every QR pointed at a port
//! with nothing behind it. The phone's error - "this site can't be reached" -
//! named neither cause.
//!
//! So the built page is compiled in. One process, one port, nothing to start
//! alongside it, and no way for the two halves to be out of step with each
//! other: the page a phone loads is the page this binary was built from.
//!
//! `web/dist` missing is **not** an error. A plain `cargo build` - CI's, or a
//! contributor's who is only touching the engine - should not need Node
//! installed. The table simply comes out empty and the server says so in a way
//! that names the fix, rather than the build failing somewhere far from it.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let dist = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../web/dist");
    println!("cargo:rerun-if-changed=build.rs");
    // The directory itself, so that *creating* it after a build without one
    // rebuilds rather than leaving an app that serves nothing.
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut files = Vec::new();
    collect(&dist, &dist, &mut files);
    files.sort();

    // Every file by name, and not just the directory above.
    //
    // A directory's mtime does not change when a file *inside* it is rewritten,
    // and Vite rewrites `index.html` in place on every build. Watching only the
    // directory therefore misses the most common edit there is, and the app
    // goes on serving the page it was first built with - which is precisely the
    // "my change did not land" that is impossible to debug from the phone,
    // because the phone is faithfully showing what it was sent.
    for (_, disk_path) in &files {
        println!("cargo:rerun-if-changed={}", disk_path.display());
    }

    let mut out = String::new();
    out.push_str(
        "// Generated by build.rs from web/dist. Do not edit.\n\
         pub static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for (url_path, disk_path) in &files {
        // A path is only ever produced by walking the directory, so it cannot
        // contain a quote unless someone puts one in a filename; escape anyway
        // rather than emit Rust that does not compile.
        let _ = writeln!(
            out,
            "    ({:?}, {:?}, include_bytes!({:?})),",
            url_path,
            mime_of(url_path),
            disk_path.display().to_string(),
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("page_assets.rs");
    std::fs::write(&dest, out).expect("writing the asset table");

    if files.is_empty() {
        println!(
            "cargo:warning=web/dist is empty or missing, so PadRemote will not \
             serve the phone page. Run `npm ci && npm run build` in web/, or use \
             ./install.sh which does it for you."
        );
    }
}

/// Every file under `dir`, as (URL path, path on disk).
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
            continue;
        }
        // `.DS_Store` and friends are not part of the page and would be served
        // to anyone who asked for them by name.
        if path
            .file_name()
            .is_some_and(|n| n.to_string_lossy().starts_with('.'))
        {
            continue;
        }
        let Ok(rel) = path.strip_prefix(root) else {
            continue;
        };
        let url = format!("/{}", rel.to_string_lossy().replace('\\', "/"));
        out.push((url, path));
    }
}

/// The `Content-Type` for a path, by extension.
///
/// Wrong types here are not cosmetic: a stylesheet served as `text/plain` is
/// ignored by every browser, and a module served as anything but JavaScript
/// fails to load with a console message most people never see.
fn mime_of(path: &str) -> &'static str {
    let ext = path.rsplit_once('.').map(|(_, e)| e).unwrap_or("");
    match ext {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "svg" => "image/svg+xml",
        "json" => "application/json; charset=utf-8",
        "webmanifest" => "application/manifest+json; charset=utf-8",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "ttf" => "font/ttf",
        "txt" => "text/plain; charset=utf-8",
        "map" => "application/json; charset=utf-8",
        _ => "application/octet-stream",
    }
}
